### ISSUE TITLE
centos7のvmにprometeus/grafanaを導入するぞ

### ISSUE THREAD

**Issue by sataga** [easy-to-study/FY20_prometheus_training#3]
# リンク

## vm環境構築
- [x] [MacにVagrantでCentOS7環境を作成 - Qiita](https://qiita.com/sudachi808/items/3614fd90f9025973de4b)
  - [x] [Vagrantで起動したCentOS7にLAMP環境を構築しHelloWorldを表示する | プログラマーを目指す 「中卒」 男のブログ](https://chusotsu-program.com/vagrant-lamp/)

## 各種インストール
- [x] [Prometheus 環境構築手順 - Qiita](https://qiita.com/tSU_RooT/items/fec5b9217417758988ae#rules%E6%96%87%E6%B3%95%E3%81%AE%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF)
- [x] [CentOS7にPrometheusをInstall - Qiita](https://qiita.com/kyo662211/items/90eefc247d44cb9f20bb)
- [x] [Prometheusを使用してCentOS 7サーバーを監視する方法](https://www.codeflow.site/ja/article/how-to-use-prometheus-to-monitor-your-centos-7-server)
- [x] [p-lux.net - CentOS 7 に Grafanaをインストールしてみた覚書](https://p-lux.net/?no=2391)

## メール通知
- [x] [Prometheus でメール通知 | SIOS Tech. Lab](https://tech-lab.sios.jp/archives/16604)
- [x] [【Azureでメールサーバ #1】 送信メールを迷惑メールにさせない方法!! | SIOS Tech. Lab](https://tech-lab.sios.jp/archives/2401)

## Slack通知
- https://github.com/easy-to-study/FY20_prometheus_training/issues/7

**Comment by c-tsukamoto** [comment]
nginx install 時のコマンド
```
rpm -ivh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
yum install nginx
```

公式ページ
http://nginx.org/en/linux_packages.html#stable

**Comment by c-tsukamoto** [comment]
prometheus -> alertmanagerメモ

prometheus.yml
targets にて alertmanager を指定
rule_files にて任意のファイルを指定
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - alert_rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9100']
```

alert_rules.yml
CPU 使用率が50%を1m間超過したら通知するよう設定
```
groups:
  - name: sample_alert
    rules:
      - alert: AlertTest
        expr: rate(node_cpu_seconds_total{instance="10.0.0.5:9100", job="prometheus", mode="user"}[5m]) > 0.5
        for: 1m
        labels:
          severity: test
          test_type: SampleAlert
        annotations:
          summary: sample_alert
```

alertmanager.yml にて通知方法を設定(メール飛ばせてないのでまだですｍ)
