### ISSUE TITLE
いろんなアラートルールを試してみる

### ISSUE THREAD

**Issue by sataga** [easy-to-study/FY20_prometheus_training#9]
公式
---
- [Alerting rules | Prometheus](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/)

事例集
---
- [Awesome Prometheus alerts | Collection of alerting rules](https://awesome-prometheus-alerts.grep.to/rules.html)

おまけ
---
ついででpromtoolの練習をする
<details>
<summary>HELP</summary>

```
[root@staga-test prometheus]# promtool
usage: promtool [<flags>] <command> [<args> ...]

Tooling for the Prometheus monitoring system.

Flags:
  -h, --help     Show context-sensitive help (also try --help-long and --help-man).
      --version  Show application version.

Commands:
  help [<command>...]
    Show help.

  check config <config-files>...
    Check if the config files are valid or not.

  check rules <rule-files>...
    Check if the rule files are valid or not.

  check metrics
    Pass Prometheus metrics over stdin to lint them for consistency and correctness.

    examples:

    $ cat metrics.prom | promtool check metrics

    $ curl -s http://localhost:9090/metrics | promtool check metrics

  query instant <server> <expr>
    Run instant query.

  query range [<flags>] <server> <expr>
    Run range query.

  query series --match=MATCH [<flags>] <server>
    Run series query.

  query labels <server> <name>
    Run labels query.

  debug pprof <server>
    Fetch profiling debug information.

  debug metrics <server>
    Fetch metrics debug information.

  debug all <server>
    Fetch all debug information.

  test rules <test-rule-file>...
    Unit tests for rules.
```

</details>

**Comment by sataga** [comment]
何個か登録した中でのcheckしてみた。
問題の有無については事前にわかりそうな点は良いとおもった。
修正内容：group名を指定していなかったのを追加後、インデント改めたらSuccessになった
```
[root@staga-test prometheus]# promtool check rules prometheus-server/rules.yml 
Checking prometheus-server/rules.yml
  FAILED:
prometheus-server/rules.yml: 2:5: Groupname should not be empty
prometheus-server/rules.yml: 11:5: Groupname should not be empty
prometheus-server/rules.yml: 11:5: groupname: "" is repeated in the same file
prometheus-server/rules.yml: 20:5: Groupname should not be empty
prometheus-server/rules.yml: 20:5: groupname: "" is repeated in the same file

[root@staga-test prometheus]# promtool check rules prometheus-server/rules.yml 
Checking prometheus-server/rules.yml
  SUCCESS: 3 rules found
```

**Comment by sataga** [comment]
一旦4つのアラートにした

prometheus/rules.yml
---
```
groups:
  - name: example
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 5m
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

    - alert: HostHighCpuLoad
      expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Host high CPU load (instance {{ $labels.instance }})"
        description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: HostOutOfMemory
      expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Host out of memory (instance {{ $labels.instance }})"
        description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: HostOutOfDiskSpace
      expr: (node_filesystem_avail_bytes{device="rootfs"}  * 100) / node_filesystem_size_bytes{device="rootfs"} < 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Host out of disk space (instance {{ $labels.instance }})"
        description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"  
```

チェック結果
---
```
[root@staga-test prometheus]# promtool check rules prometheus-server/rules.yml 
Checking prometheus-server/rules.yml
  SUCCESS: 4 rules found

[root@staga-test prometheus]# 
```
